services:
  - type: web
    name: medical-device-litigation-benchmark
    env: static
    buildCommand: echo "No build required"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /data/*
        name: Cache-Control
        value: public, max-age=3600, must-revalidate
