# Default configuration file for medical device classification benchmark

# Data configuration
data:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
  splits_path: "data/splits/"
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  random_seed: 42
  
  # Image processing settings
  image_size: [224, 224]
  augmentation: true
  normalization:
    mean: [0.485, 0.456, 0.406]  # ImageNet mean
    std: [0.229, 0.224, 0.225]   # ImageNet std
  
  # Text processing settings
  max_sequence_length: 512
  vocab_size: 10000

# Model configurations
models:
  mlp:
    hidden_dims: [512, 256, 128]
    dropout: 0.2
    activation: "relu"
    batch_norm: true
    
  cnn:
    base_filters: 64
    num_conv_blocks: 3
    kernel_size: 3
    pooling: "max"
    dropout: 0.5
    
  transformer:
    embed_dim: 256
    num_heads: 8
    num_layers: 4
    feedforward_dim: 1024
    dropout: 0.1

# Training configuration
training:
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.001
  optimizer: "adam"
  weight_decay: 1e-4
  
  # Learning rate scheduling
  lr_scheduler:
    type: "step"
    step_size: 30
    gamma: 0.1
  
  # Early stopping
  early_stopping:
    patience: 10
    min_delta: 0.001
    monitor: "val_f1_score"
  
  # Model checkpointing
  checkpoint:
    save_best: true
    save_last: true
    monitor: "val_f1_score"

# Evaluation configuration
evaluation:
  metrics:
    - "accuracy"
    - "precision" 
    - "recall"
    - "f1_score"
    - "roc_auc"
    - "confusion_matrix"
  
  cross_validation:
    enabled: false
    n_folds: 5
    stratified: true
  
  statistical_tests:
    enabled: true
    alpha: 0.05

# Benchmark configuration
benchmark:
  output_directory: "benchmarks/"
  generate_report: true
  generate_plots: true
  save_predictions: true
  
  # Visualization settings
  plots:
    confusion_matrix: true
    roc_curves: true
    precision_recall_curves: true
    training_curves: true
    
# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/benchmark.log"

# Device categories for classification
device_categories:
  - "Diagnostic Imaging"
  - "Surgical Instruments" 
  - "Monitoring Equipment"
  - "Therapeutic Devices"
  - "Prosthetics"
  - "Implants"
  - "Laboratory Equipment"
  - "Emergency Equipment"
  - "Rehabilitation Devices"
  - "Dental Equipment"